export enum ProfileActionTypes {
    SET_USER_PROFILE_DATA = 'PROFILE/SET_USER_PROFILE_DATA',
    SET_USER_STATUS = 'PROFILE/SET_USER_STATUS',
    SET_IS_LOADED_USER_DATA = 'PROFILE/SET_IS_LOADED_USER_DATA',
    SET_USER_PHOTO = 'PROFILE/SET_USER_PHOTO',
    CHANGE_USER_DATA = 'PROFILE/CHANGE_USER_DATA'
}
