export const SET_USER_PROFILE_DATA = 'PROFILE/SET_USER_PROFILE_DATA';
export const SET_USER_STATUS = 'PROFILE/SET_USER_STATUS';
export const SET_IS_LOADED_USER_DATA = 'PROFILE/SET_IS_LOADED_USER_DATA';