export const GET_USERS = 'GET_USERS';
export const SET_USERS = 'SET_USERS';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_FOLLOW = 'TOGGLE_FOLLOW';
export const TOGGLE_FOLLOW_IN_PROGRESS = 'TOGGLE_FOLLOW_IN_PROGRESS';
export const CLEAR_USERS_LIST = 'CLEAR_USERS_LIST';