export enum UsersActionTypes {
    GET_USERS = 'USERS/GET_USERS',
    SET_USERS = 'USERS/SET_USERS',
    CHANGE_PAGE_SIZE = 'USERS/CHANGE_PAGE_SIZE',
    CHANGE_CURRENT_PAGE = 'USERS/CHANGE_CURRENT_PAGE',
    TOGGLE_LOADING = 'USERS/TOGGLE_LOADING',
    TOGGLE_FOLLOW = 'USERS/TOGGLE_FOLLOW',
    TOGGLE_FOLLOW_IN_PROGRESS = 'USERS/TOGGLE_FOLLOW_IN_PROGRESS',
    CLEAR_USERS_LIST = 'USERS/CLEAR_USERS_LIST'
}
