export const GET_USERS = 'USERS/GET_USERS';
export const SET_USERS = 'USERS/SET_USERS';
export const CHANGE_PAGE_SIZE = 'USERS/CHANGE_PAGE_SIZE';
export const CHANGE_PAGE_NUMBER = 'USERS/CHANGE_PAGE_NUMBER';
export const TOGGLE_LOADING = 'USERS/TOGGLE_LOADING';
export const TOGGLE_FOLLOW = 'USERS/TOGGLE_FOLLOW';
export const TOGGLE_FOLLOW_IN_PROGRESS = 'USERS/TOGGLE_FOLLOW_IN_PROGRESS';
export const CLEAR_USERS_LIST = 'USERS/CLEAR_USERS_LIST';