export const GET_USERS = 'GET_USERS';
export const SET_USERS = 'SET_USERS';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';